# Generated by Django 3.0.8 on 2021-02-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled', max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
